apiVersion: apps/v1 
kind: Deployment
metadata:
  name: emal
  labels: 
     app: app

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: 034362058188.dkr.ecr.ap-south-1.amazonaws.com/charanecr:github.sha
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
